#-------------------------------
# General Site Settings
title: log
logo: ../favicon.ico # You can add own logo.
description: log
timezone: Asia/Seoul 

#-------------------------------
# Author Settings
author:
  name: log
  image: covers.jpg
  say-hello: Hello, I’m <strong>Machine Learning Developer.</strong>
  bio: 포스팅은 주로 머신러닝과 R, PYTHON에 대해 쓰고 있습니다. 모든 포스팅에서 사용된 코드와 데이터는 Github에 있습니다. 


#-------------------------------
# Contact links
#twitter: https://twitter.com/ # Add your Twitter handle
#facebook: https://facebook.com/ # Add your Facebook handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://www.instagram.com/ao_ej125/ # Add your Instagram handle
github: https://github.com/KEJdev/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: ao_ej125 # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: UA-148043528-1 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
# mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e